swagger: "2.0"
info:
  description: "This is a API contract for Call For Service server."
  version: "1.0.0"
  title: "Swagger CallForService"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "trungee.nguyen@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "cfs.swagger.io"
basePath: "/v1"
tags:
- name: "CallForService"
  description: "Everything about your CallForService"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"

paths:
  /call-for-service:
    post:
      tags:
      - "CallForService"
      summary: "Add a new Call For Service to the system"
      description: ""
      operationId: "createCallForService"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "CallForService object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/CallForService"
      responses:
        "201":
          description: "CREATED"
          schema:
            $ref: "#/definitions/CallForService"
        "405":
          description: "Invalid input"
          
  /call-for-service/search:
    post:
      tags:
      - "CallForService"
      summary: "Search for CFS within a time range with paging and sorting order"
      description: "Returns CFSs"
      operationId: "searchByTimeRange"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/SearchRequestDto"
      responses:
        "200":
          description: "response with CFSs paged & sorted result"
          schema:
            $ref: "#/definitions/SearchResponseDto"
        "405":
          description: "Invalid input"
          
securityDefinitions:
  OAuth2:
    type: "oauth2"
    tokenUrl: "http://cfs.swagger.io/oauth/token"
    flow: "password"
    
definitions:
  SearchRequestDto:
    type: "object"
    properties:
      startTime:
        type: "string"
        format: "date-time"
      endTime:
        type: "string"
        format: "date-time"
      orderBy:
        type: "string"
      size:
        type: "number"
      pageNumber: 
        type: "number"
      orderDirection:
        type: "string"
        description: "order direction"
        enum:
        - "ASC"
        - "DESC"
  SearchResponseDto:
    type: "object"
    properties:
      content:
        type: array
        items:
          $ref: "#/definitions/CallForService"
      totalElements:
        type: "number"
      totalPages:
        type: "number"
      size:
        type: "number"
      sort:
        type: "object"
      pageNumber:
        type: "number"
    xml:
      name: "Category"
  CallForService:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "string"
        format: "uuid"
      agency_id:
        type: "string"
        format: "uuid"
      event_id:
        type: "string"
        format: "uuid"
      event_number:
        type: "string"
      event_type_code:
        type: "string"
        enum:
        - "SMO"
        - "PENDING"
      event_time:
        type: "string"
        format: "date-time"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"